import Vue from "vue";
import Page from "~/components/Page.vue";
import Teaser from "~/components/Teaser.vue";
import Bio from "~/components/Bio.vue";
import Menu from "~/components/Menu.vue";
import MenuMonth from "~/components/MenuMonth.vue";
import MenuItem from "~/components/MenuItem.vue";
import MenuArchivePage from "~/components/MenuArchivePage.vue";
import Richtext from "~/components/Richtext.vue";
import Contact from "~/components/Contact.vue";
import Services from "~/components/Services.vue";
import Service from "~/components/Service.vue";
import ServicePrice from "~/components/ServicePrice.vue";
import CallToAction from "~/components/CallToAction.vue";
import Masthead from "~/components/Masthead.vue";
import Instagram from "~/components/Instagram.vue";
import Availability from "~/components/Availability.vue";

Vue.component("blok-page", Page);
Vue.component("blok-teaser", Teaser);
Vue.component("blok-bio", Bio);
Vue.component("rich-text", Richtext);
Vue.component("blok-menu", Menu);
Vue.component("blok-menu-month", MenuMonth);
Vue.component("blok-menu-item", MenuItem);
Vue.component("blok-menu-archive-page", MenuArchivePage);
Vue.component("blok-contact", Contact);
Vue.component("blok-services", Services);
Vue.component("blok-service", Service);
Vue.component("blok-service-price", ServicePrice);
Vue.component("blok-call-to-action", CallToAction);
Vue.component("blok-masthead", Masthead);
Vue.component("blok-instagram", Instagram);
Vue.component("blok-availability", Availability);
